# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            The Sapzil
tagline:          Ditto Kim's Dev Log
url:              https://dittos.github.io
paginate:         1
baseurl:          /
author:
  name:           Ditto Kim
  url:            https://twitter.com/__ditto
  email:          dittos@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
