# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:           pretty

# Setup
title:            The Sapzil
tagline:          Ditto Kim's Dev Log
url:              http://blog.sapzil.org
paginate:         10
baseurl:          ""
analytics_id:     UA-7500828-6
future:           true

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:           Ditto Kim
  url:            https://twitter.com/needkoolquality
  email:          dittos@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole
date_format: "%Y년 %m월 %d일"

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
